Add the ability to do backups to remote systems with rsync

diff --git a/templates/scheduled_backup.sh.j2 b/templates/scheduled_backup.sh.j2
--- a/templates/scheduled_backup.sh.j2
+++ b/templates/scheduled_backup.sh.j2
@@ -10,6 +10,8 @@ mailto='{{ postgresql_backup_mail_recipient }}'
 mutex='{{ postgresql_backup_local_dir }}/nightlymutex'
 rotate='{{ postgresql_backup_rotate | default("True") }}'
 
+[ '{{ postgresql_backup_remote_rsync_path | default("None") }}' != 'None' ] && remote_rsync='--rsync-path={{ postgresql_backup_remote_rsync_path }}' || remote_rsync=''
+
 handler()
 {
     command=$@
@@ -53,6 +55,9 @@ psql_handler()
     fi
 }
 
+[[ "$dir" == *':'* ]] && dir_is_remote=1
+[ "$dir_is_remote" -a $rotate != "False" ] && { echo "error: rotation with remote backup directory is not implemented" | mail -s "$server: Postgres nightly backup failed" $mailto ; exit 1 ; }
+
 [ ! -d `dirname $mutex` ] && handler mkdir -p `dirname $mutex`
 
 while [ -f $mutex ]; do
@@ -63,24 +68,22 @@ start=`date +%s`
 
 echo "nightly $$" > $mutex
 
-# move previous backup
-if [ -d $dir ]; then
-    if [ $rotate = "True" ]; then
+if [ ! "$dir_is_remote" ]; then
+    # move previous backup
+    if [ -d $dir -a $rotate = "True" ]; then
         handler mv $dir {{ postgresql_backup_dir }}/`date -u +%Y%m%dT%H%M%SZ`
-    else
-        handler rm -rf $dir
     fi
 fi
-
-# set up new directory
-handler mkdir -p $dir
 
 # tell postgres we'll be backing up
 psql_handler "SELECT pg_start_backup('$dir');"
 backup_started=1
 
+# ensure the local wal/ directory exists, so rsync creates it for wal archival
+handler mkdir -p $data/wal
+
 # begin the backup
-handler rsync -a --exclude pg_xlog $data/ $dir
+handler rsync $remote_rsync -rptg --delete --delete-delay --exclude pg_xlog $data/ $dir
 
 # tell postgres we're done
 psql_handler "SELECT pg_stop_backup();"
